### ISSUE TITLE
[1.11] `java.lang.NoClassDefFoundError: org/sqlite/NativeDB` caused by SQLite driver

### ISSUE THREAD

**Issue by RoyCurtis** [Hidendra/LWC#953]
If LWC's `database.adapter` is set to `sqlite` (which it is by default), [LWC attempts to download the SQLite native driver](https://github.com/Hidendra/LWC/blob/master/core/src/main/java/com/griefcraft/util/Updater.java) and [unpacks it into its plugin directory](http://i.imgur.com/GFewaOo.png). This driver is then loaded in some fashion.

In Spigot 1.11, [Spigot's bundled SQLite driver has been updated to the 3.14 series](https://www.spigotmc.org/threads/bukkit-1-11-api-draft.193437/). This appears to conflict with the SQLite driver that LWC downloads and loads, breaking all other plugins that use SQLite:

* [CraftBook: `java.lang.NoClassDefFoundError: org/sqlite/NativeDB`](https://gist.github.com/RoyCurtis/38aa4f90091e9c1de7d7f85c68fd3f77)
* [SignShop: `java.lang.NoClassDefFoundError: org/sqlite/NativeDB`](https://gist.github.com/RoyCurtis/f33ae41b35176efc86d2b0cc4c026cd1)
* [WorldGuard: `java.lang.NoClassDefFoundError: org/sqlite/NativeDB`](https://gist.github.com/RoyCurtis/a1fc696f2c9d6c126e2a24cbbd311abb)
* [TicketMaster: `java.lang.NoClassDefFoundError: org/sqlite/NativeDB`](https://gist.github.com/RoyCurtis/daa60e40cd19b40f427c72cbf165e125)

# Details

* Tested on `CraftBukkit version git-Spigot-16c940b-88eede8 (MC: 1.11) (Implementing API version 1.11-R0.1-SNAPSHOT)`
* Tested with [LWC build 941](http://ci.griefcraft.com/job/LWC/941/)
* `Plugins (28): CleanroomGenerator, dynmap, WorldEdit, Titanic, zPermissions, Chairs, WorldBorder, TicketMaster, ProtocolLib, Multiverse-Core, WorldGuard, NoCheatPlus, WoodCutter, Stables, Multiverse-SignPortals, HappyPet, Multiverse-Portals, Vault, Prism, Essentials, PerWorldInventory, LWC, SignShop, VanishNoPacket, SignShopExport, CraftBook, Multiverse-NetherPortals, PurpleIRC`

# Reproduction

1. Prepare a Spigot 1.11 server
2. Put LWC, [WorldGuard](http://builds.enginehub.org/job/worldguard) and [CraftBook](http://ci.md-5.net/job/CraftBook/) in the plugins folder
3. Start the server. Note that WorldGuard and CraftBook fail to load with a `NoClassDefFoundError` exception
4. Stop the server and remove LWC from the plugins folder
5. Start the server. Observe that WorldGuard and CraftBook now load as expected

# Workaround

* If LWC's `config.yml` is set to use `mysql` as the adapter, try deleting `plugins/LWC/lib`
* If LWC's `config.yml` is set to use `sqlite` as the adapter, you must migrate to and use MySQL instead

# Notes

* [This issue was reported on Spigot's JIRA as SPIGOT-2783](https://hub.spigotmc.org/jira/browse/SPIGOT-2783)
* Personally, I find it concerning that LWC downloads and executes a _native library_ from a third-party website (http://update.griefcraft.com) _by default_. I wonder also, why bother attempting to download or package SQLite when Spigot already has it?

**Comment by TNTUP** [comment]
Delete the file lib/.../.../libsqlite something.so or edit it and delete everything in and save it so it<ll reach 0 bytes, but you'll see that notice but it can be freely ignored. Restart server and LWC will start.

**Comment by jordanwilliams1** [comment]
@TNTUP Doesn't work on paper

**Comment by RoyCurtis** [comment]
@jordanwilliams1 In your LWC's `config.yml`, what is `adapter` under `database` set to? Are you using `mysql` or `sqlite`?

**Comment by jordanwilliams1** [comment]
@RoyCurtis sqlite but don't really fancy changing to mysql.

**Comment by TNTUP** [comment]
@jordanwilliams1 Then you're doing something wrong. LWC works fine on my Paper 1.10.2/1.11 server.

**Comment by jordanwilliams1** [comment]
@TNTUP http://pastebin.com/raw/ryuAeHrm

**Comment by TNTUP** [comment]
Follow my steps, go in /plugins/LWC/lib/native/linux/amd64/ and (don’t delete the .so file!!) edit it, cut ALL strings inside of the file then save! It will save at 0 bytes so the file is « invalid » but! LWC will try to load the integrated sqlite in spigot/paper jars! Though, there will be a Java VM warning because the file is « too short » but safe to ignore on my side, tested locking shulkerboxes, everyting works! ☺

De : jordanwilliams1 [mailto:notifications@github.com]
Envoyé : 28 novembre 2016 16:58
À : Hidendra/LWC <LWC@noreply.github.com>
Cc : Yann <fluorescent92@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [Hidendra/LWC] [1.11] `java.lang.NoClassDefFoundError: org/sqlite/NativeDB` caused by SQLite driver (#953)


@TNTUP<https://github.com/TNTUP> http://pastebin.com/raw/ryuAeHrm
