### ISSUE TITLE
latest LWC not working with 1.11.2 

### ISSUE THREAD

**Issue by HellOnBlocks** [Hidendra/LWC#956]
Error:
[12:28:08] [Server thread/ERROR]: Error occurred while enabling LWC v4.5.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/sqlite/NativeDB
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadLibrary0(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadLibrary(Unknown Source) ~[?:1.8.0_121]
	at java.lang.Runtime.load0(Unknown Source) ~[?:1.8.0_121]
	at java.lang.System.load(Unknown Source) ~[?:1.8.0_121]
	at org.sqlite.SQLiteJDBCLoader.loadNativeLibrary(SQLiteJDBCLoader.java:272) ~[spigot.jar:git-Spigot-65a0347-a552117]
	at org.sqlite.SQLiteJDBCLoader.loadSQLiteNativeLibrary(SQLiteJDBCLoader.java:308) ~[spigot.jar:git-Spigot-65a0347-a552117]
	at org.sqlite.SQLiteJDBCLoader.initialize(SQLiteJDBCLoader.java:64) ~[spigot.jar:git-Spigot-65a0347-a552117]
	at org.sqlite.core.NativeDB.load(NativeDB.java:56) ~[spigot.jar:git-Spigot-65a0347-a552117]
	at org.sqlite.core.CoreConnection.open(CoreConnection.java:211) ~[spigot.jar:git-Spigot-65a0347-a552117]
	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76) ~[spigot.jar:git-Spigot-65a0347-a552117]
	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:26) ~[spigot.jar:git-Spigot-65a0347-a552117]
	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24) ~[spigot.jar:git-Spigot-65a0347-a552117]
	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45) ~[spigot.jar:git-Spigot-65a0347-a552117]
	at org.sqlite.JDBC.createConnection(JDBC.java:114) ~[spigot.jar:git-Spigot-65a0347-a552117]
	at org.sqlite.JDBC.connect(JDBC.java:88) ~[spigot.jar:git-Spigot-65a0347-a552117]
	at com.griefcraft.sql.Database.connect(Database.java:250) ~[?:?]
	at com.griefcraft.lwc.LWC.load(LWC.java:1503) ~[?:?]
	at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:203) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[spigot.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot.jar:git-Spigot-65a0347-a552117]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot.jar:git-Spigot-65a0347-a552117]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-65a0347-a552117]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassNotFoundException: org.sqlite.NativeDB
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
	... 27 more

Any advice?

**Comment by taberruu** [comment]
Have a look at this: https://github.com/Hidendra/LWC/issues/953

**Comment by Chew** [comment]
`INFO java.lang.NoClassDefFoundError: org/sqlite/NativeDB`
A plugin is loading its own conflicting version of SQLite instead of using the one bundled with CraftBukkit/Spigot
Check this:
https://github.com/Hidendra/LWC/issues/953
and this:
https://hub.spigotmc.org/jira/browse/SPIGOT-2783
